# -*- coding: utf-8 -*-
"""chatbot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11yCuHRrbkHtKGBHD0WA2So2X7WxHomhG
"""

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_community.llms import Ollama
import streamlit as st

st.title("DIYA CHATBOT")
st.caption("The Website is under maintanence, sorry for the late responses.")
input_txt = st.text_input("Ask Anything...")


submit = st.button("Submit")
prompt = ChatPromptTemplate.from_messages(
    [("system","you are a generative AI Assistant. Your name is diya"),
     ("user","user query:{query}")]
)

llm = Ollama(model="llama2")
output_parser = StrOutputParser()
chain = prompt|llm|output_parser

if input_txt:
  st.write(chain.invoke({"query":input_txt}))